src/GalleryUploader.swf: src/GalleryUploader.mxml src/com/gallery/shell/GalleryUploaderBase.as src/com/gallery/uploader/UploaderBase.as src/com/gallery/uploader/ProgressRendererBase.as
	mxmlc src/GalleryUploader.mxml
